import { IUser } from ".";

export const data: IUser[] = [
  {
    id: 1,
    name: "Đặng Hoàng Phúc",
    major: "Frontend Developer",
    address: "Ốc đảo Bình Chánh",
    gender: true,
    salary: 5000000,
  },
  {
    id: 2,
    name: "Lê Khánh Phương",
    major: "Right Arm of VTCODE & PPA Smart",
    address: "KĐT Sala",
    gender: true,
    salary: 30000000,
  },
  {
    id: 3,
    name: "Trần Nguyên Khánh",
    major: "Backend Developer",
    address: "Cư dân xóm ngập Q8",
    gender: true,
    salary: 15000000,
  },
  {
    id: 4,
    name: "Phạm Anh Dũng",
    major: "Mobile Developer",
    address: "Dân ở xa cô đơn Gò Vấp",
    gender: true,
    salary: 20000000,
  },
  {
    id: 5,
    name: "Trần Thị Ngọc Thùy",
    major: "Website Developer",
    address: "Kho trung chuyển Shopee",
    gender: false,
    salary: 20000000,
  },
  {
    id: 6,
    name: "Nguyễn Văn A",
    major: "Data Scientist",
    address: "Hanoi, Vietnam",
    gender: true,
    salary: 25000000,
  },
  {
    id: 7,
    name: "Nguyễn Thị B",
    major: "UX/UI Designer",
    address: "Ho Chi Minh City, Vietnam",
    gender: false,
    salary: 18000000,
  },
  {
    id: 8,
    name: "Trần Đình C",
    major: "Software Engineer",
    address: "Da Nang, Vietnam",
    gender: true,
    salary: 22000000,
  },
  {
    id: 9,
    name: "Lê Thị D",
    major: "Database Administrator",
    address: "Hai Phong, Vietnam",
    gender: false,
    salary: 19000000,
  },
  {
    id: 10,
    name: "Hoàng Văn E",
    major: "Cybersecurity Analyst",
    address: "Can Tho, Vietnam",
    gender: true,
    salary: 28000000,
  },
  {
    id: 11,
    name: "Phạm Văn F",
    major: "Network Engineer",
    address: "Hanoi, Vietnam",
    gender: true,
    salary: 23000000,
  },
  {
    id: 12,
    name: "Nguyễn Thị G",
    major: "Full Stack Developer",
    address: "Ho Chi Minh City, Vietnam",
    gender: false,
    salary: 26000000,
  },
  {
    id: 13,
    name: "Lê Văn H",
    major: "System Analyst",
    address: "Da Nang, Vietnam",
    gender: true,
    salary: 21000000,
  },
  {
    id: 14,
    name: "Trần Thị I",
    major: "Software Tester",
    address: "Hai Phong, Vietnam",
    gender: false,
    salary: 17000000,
  },
  {
    id: 15,
    name: "Nguyễn Văn K",
    major: "DevOps Engineer",
    address: "Can Tho, Vietnam",
    gender: true,
    salary: 27000000,
  },
  {
    id: 16,
    name: "Hoàng Thị L",
    major: "Web Designer",
    address: "Hanoi, Vietnam",
    gender: false,
    salary: 20000000,
  },
  {
    id: 17,
    name: "Trần Văn M",
    major: "Software Architect",
    address: "Ho Chi Minh City, Vietnam",
    gender: true,
    salary: 29000000,
  },
  {
    id: 18,
    name: "Lê Thị N",
    major: "Machine Learning Engineer",
    address: "Da Nang, Vietnam",
    gender: false,
    salary: 24000000,
  },
  {
    id: 19,
    name: "Phạm Văn O",
    major: "Cloud Engineer",
    address: "Hai Phong, Vietnam",
    gender: true,
    salary: 30000000,
  },
  {
    id: 20,
    name: "Nguyễn Thị P",
    major: "Frontend Developer",
    address: "Can Tho, Vietnam",
    gender: false,
    salary: 21000000,
  },
  {
    id: 21,
    name: "Lê Văn Q",
    major: "Backend Developer",
    address: "Hanoi, Vietnam",
    gender: true,
    salary: 22000000,
  },
  {
    id: 22,
    name: "Trần Thị R",
    major: "Mobile Developer",
    address: "Ho Chi Minh City, Vietnam",
    gender: false,
    salary: 23000000,
  },
  {
    id: 23,
    name: "Nguyễn Văn S",
    major: "Database Developer",
    address: "Da Nang, Vietnam",
    gender: true,
    salary: 25000000,
  },
  {
    id: 24,
    name: "Hoàng Thị T",
    major: "Game Developer",
    address: "Hai Phong, Vietnam",
    gender: false,
    salary: 26000000,
  },
  {
    id: 25,
    name: "Trần Văn U",
    major: "Embedded Systems Engineer",
    address: "Can Tho, Vietnam",
    gender: true,
    salary: 27000000,
  },
  {
    id: 26,
    name: "Lê Thị V",
    major: "IT Consultant",
    address: "Hanoi, Vietnam",
    gender: false,
    salary: 28000000,
  },
  {
    id: 27,
    name: "Phạm Văn W",
    major: "Cybersecurity Analyst",
    address: "Ho Chi Minh City, Vietnam",
    gender: true,
    salary: 29000000,
  },
  {
    id: 28,
    name: "Nguyễn Thị X",
    major: "Software Engineer",
    address: "Da Nang, Vietnam",
    gender: false,
    salary: 30000000,
  },
  {
    id: 29,
    name: "Lê Văn Y",
    major: "UX/UI Designer",
    address: "Hai Phong, Vietnam",
    gender: true,
    salary: 31000000,
  },
  {
    id: 30,
    name: "Trần Thị Z",
    major: "Data Scientist",
    address: "Can Tho, Vietnam",
    gender: false,
    salary: 32000000,
  },
  {
    id: 31,
    name: "Nguyễn Văn AA",
    major: "Frontend Developer",
    address: "Hanoi, Vietnam",
    gender: true,
    salary: 33000000,
  },
  {
    id: 32,
    name: "Hoàng Thị BB",
    major: "Software Engineer",
    address: "Ho Chi Minh City, Vietnam",
    gender: false,
    salary: 34000000,
  },
  {
    id: 33,
    name: "Trần Văn CC",
    major: "Database Administrator",
    address: "Da Nang, Vietnam",
    gender: true,
    salary: 35000000,
  },
  {
    id: 34,
    name: "Lê Thị DD",
    major: "Network Engineer",
    address: "Hai Phong, Vietnam",
    gender: false,
    salary: 36000000,
  },
  {
    id: 35,
    name: "Phạm Văn EE",
    major: "Full Stack Developer",
    address: "Can Tho, Vietnam",
    gender: true,
    salary: 37000000,
  },
  {
    id: 36,
    name: "Nguyễn Thị FF",
    major: "System Analyst",
    address: "Hanoi, Vietnam",
    gender: false,
    salary: 38000000,
  },
  {
    id: 37,
    name: "Lê Văn GG",
    major: "Software Tester",
    address: "Ho Chi Minh City, Vietnam",
    gender: true,
    salary: 39000000,
  },
  {
    id: 38,
    name: "Trần Thị HH",
    major: "DevOps Engineer",
    address: "Da Nang, Vietnam",
    gender: false,
    salary: 40000000,
  },
  {
    id: 39,
    name: "Nguyễn Văn II",
    major: "Web Designer",
    address: "Hai Phong, Vietnam",
    gender: true,
    salary: 41000000,
  },
  {
    id: 40,
    name: "Hoàng Thị KK",
    major: "Software Architect",
    address: "Can Tho, Vietnam",
    gender: false,
    salary: 42000000,
  },
  {
    id: 41,
    name: "Trần Văn LL",
    major: "Machine Learning Engineer",
    address: "Hanoi, Vietnam",
    gender: true,
    salary: 43000000,
  },
  {
    id: 42,
    name: "Lê Thị MM",
    major: "Cloud Engineer",
    address: "Ho Chi Minh City, Vietnam",
    gender: false,
    salary: 44000000,
  },
  {
    id: 43,
    name: "Phạm Văn NN",
    major: "Frontend Developer",
    address: "Da Nang, Vietnam",
    gender: true,
    salary: 45000000,
  },
  {
    id: 44,
    name: "Nguyễn Thị OO",
    major: "Backend Developer",
    address: "Hai Phong, Vietnam",
    gender: false,
    salary: 46000000,
  },
  {
    id: 45,
    name: "Lê Văn PP",
    major: "Mobile Developer",
    address: "Can Tho, Vietnam",
    gender: true,
    salary: 47000000,
  },
  {
    id: 46,
    name: "Trần Thị QQ",
    major: "Database Developer",
    address: "Hanoi, Vietnam",
    gender: false,
    salary: 48000000,
  },
  {
    id: 47,
    name: "Nguyễn Văn RR",
    major: "Game Developer",
    address: "Ho Chi Minh City, Vietnam",
    gender: true,
    salary: 49000000,
  },
  {
    id: 48,
    name: "Hoàng Thị SS",
    major: "Embedded Systems Engineer",
    address: "Da Nang, Vietnam",
    gender: false,
    salary: 50000000,
  },
];
